# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install coveralls

script:
  - coverage run tests/test_script_io.py
  - coverage run tests/test_script_inplace.py
  - coverage run tests/test_suite.py @all-tests.suites -x test-python-sed.exclude

after_success:
  - coveralls
