# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false


install:
  - pip install .
  - pip install coveralls

script:
  - coverage run tests/test-suite.py @all-tests.suites -x test-python-sed.exclude

after_success:
  - coveralls
